In [1]:
import numpy as np

In [4]:
# same shape
np.ones(shape=(2,3)) + np.ones(shape=(2,3))

array([[2., 2., 2.],
       [2., 2., 2.]])

In [6]:
# broadcasting first axis
# transform second array into (1,3) then into (2,3)
np.ones(shape=(2,3)) + np.ones(shape=(3))

array([[2., 2., 2.],
       [2., 2., 2.]])

In [7]:
# same thing
np.ones(shape=(2,3)) + np.ones(shape=(1, 3))

array([[2., 2., 2.],
       [2., 2., 2.]])

In [9]:
# scalar -> (1) -> (3) -> (1,3) -> (2,3)
np.ones(shape=(2,3)) + 1

array([[2., 2., 2.],
       [2., 2., 2.]])

In [19]:
# concat arrays along 3rd axis (new)
np.stack(
    [
        np.ones(shape=(4,3)),
        np.ones(shape=(4,3)),
    ],
    axis=2
).shape

(4, 3, 2)

In [20]:
# not working! broadcasting has to be manual
try:
    np.stack(
        [
            np.ones(shape=(4,3)),
            np.ones(shape=(3)),
        ],
        axis=2
    ).shape
except ValueError as e:
    print(e)

all input arrays must have the same shape


In [22]:
# rightway is to broadcast manually first

np.stack(
        [
            np.ones(shape=(4,3)),
            np.broadcast_to(np.ones(shape=(3)), (4,3)),
        ],
        axis=2
    ).shape

(4, 3, 2)