In [26]:
import pandas as pd
import xarray as xr
import numpy as np

In [16]:
# simple multiplication table
x = np.arange(1,10)
y = np.arange(1,10)
X,Y = np.meshgrid(x,y)
data = X * Y

In [18]:
df = pd.DataFrame(data, index=y, columns=x)
xs = xr.Dataset.from_dataframe(df)

In [31]:
# Create Dataset
ds = xr.Dataset(
    data_vars=dict(
        data=(["x", "y"], data),
    ),
    coords=dict(
        x=x,
        y=y,
    ),
    attrs=dict(description="Multiplication Table"),
)
ds

<xarray.Dataset>
Dimensions:  (x: 9, y: 9)
Coordinates:
  * x        (x) int64 1 2 3 4 5 6 7 8 9
  * y        (y) int64 1 2 3 4 5 6 7 8 9
Data variables:
    data     (x, y) int64 1 2 3 4 5 6 7 8 9 2 4 ... 72 9 18 27 36 45 54 63 72 81
Attributes:
    description:  Multiplication Table

In [29]:
xr.DataArray

xarray.core.dataarray.DataArray

In [32]:
# Create DataArray
da = xr.DataArray(
    data=data,
    dims=["x", "y"],
    coords=dict(
        x=x,
        y=y,
    ),
    attrs=dict(
        description="Multiplication table",
    )
)
da

<xarray.DataArray (x: 9, y: 9)>
array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])
Coordinates:
  * x        (x) int64 1 2 3 4 5 6 7 8 9
  * y        (y) int64 1 2 3 4 5 6 7 8 9
Attributes:
    description:  Multiplication table

In [33]:
# stack several dimensions into single one
da.stack(flat=('x', 'y'))

<xarray.DataArray (flat: 81)>
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9,  2,  4,  6,  8, 10, 12, 14, 16,
       18,  3,  6,  9, 12, 15, 18, 21, 24, 27,  4,  8, 12, 16, 20, 24, 28,
       32, 36,  5, 10, 15, 20, 25, 30, 35, 40, 45,  6, 12, 18, 24, 30, 36,
       42, 48, 54,  7, 14, 21, 28, 35, 42, 49, 56, 63,  8, 16, 24, 32, 40,
       48, 56, 64, 72,  9, 18, 27, 36, 45, 54, 63, 72, 81])
Coordinates:
  * flat     (flat) MultiIndex
  - x        (flat) int64 1 1 1 1 1 1 1 1 1 2 2 2 2 ... 8 8 8 9 9 9 9 9 9 9 9 9
  - y        (flat) int64 1 2 3 4 5 6 7 8 9 1 2 3 4 ... 7 8 9 1 2 3 4 5 6 7 8 9
Attributes:
    description:  Multiplication table

In [35]:
#select using ranges
da.loc[ 5:10, 1:5 ]

<xarray.DataArray (x: 5, y: 5)>
array([[ 5, 10, 15, 20, 25],
       [ 6, 12, 18, 24, 30],
       [ 7, 14, 21, 28, 35],
       [ 8, 16, 24, 32, 40],
       [ 9, 18, 27, 36, 45]])
Coordinates:
  * x        (x) int64 5 6 7 8 9
  * y        (y) int64 1 2 3 4 5
Attributes:
    description:  Multiplication table

In [38]:
# locate using single values
da[dict(x=1)]

<xarray.DataArray (y: 9)>
array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])
Coordinates:
    x        int64 2
  * y        (y) int64 1 2 3 4 5 6 7 8 9
Attributes:
    description:  Multiplication table